### ISSUE TITLE
[Feature Request] Search by Tag → Support for tags in YAML

### ISSUE THREAD

**Issue by FelipeRearden** [ieviev/obsidian-keyboard-shortcuts#1]
Hello @aciq !!!!

First of all, thank you for creating this amazing plugin.

As a AQS heavy user, I am pretty excited about this integration. 

## My FR

Obsidian supports 2 types of tags inside the YAML
→ More info here  https://help.obsidian.md/Advanced+topics/YAML+front+matter

1️⃣ Array
```
tags: [one, two, three]
``` 

2️⃣ List
```
tags:
- four
- five
- six
``` 

Would be amazing if you could add support for these types of tag :)

---

Thanks for reading this !

Have a great day!

**Comment by ieviev** [comment]
For this i need to find if there is a cache for YAML tags. I'm currently accessing the tags from Obsidian metadata cache, which makes it very fast.

Going through the entire notes vault one and extracting yaml isn't an option so it would need to look around if someone has already done this.

**Comment by FelipeRearden** [comment]
> For this i need to find if there is a cache for YAML tags. I'm currently accessing the tags from Obsidian metadata cache, which makes it very fast.

I a created a simple templater script that gets all tags from my vault. In this script I use this `Object.keys(app.metadataCache.getTags())` 

More info here: https://github.com/SilentVoid13/Templater/discussions/756#discussioncomment-3527601

Maybe this info could help :) 

> Going through the entire notes vault one and extracting yaml isn't an option so it would need to look around if someone has already done this.

100% agree we need to find a way to get all tags without search for them inside each Note.

I really hope you find a solution for this. I almost sure that someone on Discord will  know how to get this 🙏🙏🙏

**Comment by ieviev** [comment]
Got it, frontmatter tags are stored in a separate object, now these work as well in 1.0.6

![tags-cache](https://user-images.githubusercontent.com/36763595/197311072-9aefce00-3685-400e-b798-754eb7582e91.png)

**Comment by FelipeRearden** [comment]
> Got it, frontmatter tags are stored in a separate object, now these work as well in 1.0.6

That's great news !!!!! Thank you very for this 💙

Feedback from version 1.0.6 is here https://github.com/aciq/obsidian-keyboard-shortcuts/issues/2#issuecomment-1287837605

**Comment by FelipeRearden** [comment]
Working perfect on version `1.0.7` . Thank you very much for this @aciq !!!!

You have idea how these 3 features are important for my workflow. Thank you very much :)
