### ISSUE TITLE
[Feature Request] Search by Tag → Option for Nested Tags

### ISSUE THREAD

**Issue by FelipeRearden** [ieviev/obsidian-keyboard-shortcuts#2]
Hello again @aciq !!!

Let me try explain my idea. I have a lot of tags and I use Obsidian feature of Nested Tags to organize my Tags database  

📸 My Tags
![038E72FB-5912-4F9C-9A30-DF031C21040B](https://user-images.githubusercontent.com/85180696/196532353-3f431ddc-4dfd-4f30-86be-4e624e64bf67.jpeg)

For larger Tags database, would be amazing if we could have a modal that bring the Nested Tags **folded**. 

I am gonna try to explain with an example

## Example

Let's assume that this is my Tags

```
#Source/Books
#Source/Articles
#Source/Podcasts

#Creator/Tim_Ferriss
#Creator/Ryan_Holiday

#Done
```

## My FR

1️⃣ A new modal that open my tags this way: Nested Tags are folded

```
#Source
#Creator
#Done
```

2️⃣ If I select a Nested Tag → It will open a new Modal filtered by the tags that are inside the Nested tag + Back Button `← Back`

If I select `Creator` in the first Modal, the second modal will open like this

```
#Creator/Tim_Ferriss
#Creator/Ryan_Holiday
← Back
```

---

In my opinion, this approach would make easier to search for database tags with nested tags :)

Let me know if need any additional information.

Thanks for reading !

**Comment by ieviev** [comment]
@FelipeRearden 

Sure, this is doable. 

I'm thinking maybe it should be bound to a keyboard shortcut in the modal. 

e.g. Hover #Creator, press Tab and it expands the search filter to only ones starting with creator. 

I'll find a nice way to combine this with the multiple tags option

**Comment by FelipeRearden** [comment]
Thank you very much @aciq for your reply!

> Sure, this is doable. 

Amazing! I happy to know that is feasible 
 
> I'm thinking maybe it should be bound to a keyboard shortcut in the modal. 
> 
> e.g. Hover #Creator, press Tab and it expands the search filter to only ones starting with creator. 

Fantastic idea! Tab is a great idea for shortcut key.

The main point is be able to navigate between the nested tags using ↑ ↓ and the use Tab to expand #Creator

Then use the text field to type what tag you want from the nest #Creator 

> I'll find a nice way to combine this with the multiple tags option 

Thank you very much ! I am very excited about these FRs because one of the struggles that I face with Obsidian is find/search for notes from my tag database 

Thanks again for this amazing app.

I wish you a fantastic day!!!!

**Comment by ieviev** [comment]
Implemented in 1.0.5

I added a new command: Folded search by Tag
Tab unfolds the tag further and shows count of each tag
I added both Shift+tab and Shift+enter to undo the folding / AND

**Comment by FelipeRearden** [comment]
> Implemented in 1.0.5
> 
> I added a new command: Folded search by Tag Tab unfolds the tag further and shows count of each tag I added both Shift+tab and Shift+enter to undo the folding / AND

Thank you very much ! !!!

I already tested version `1..0.6` and unfortunately the Modal from all 3 commands are **empty** in my test :(

I opened the Console and I saw this notification:

📸 Console (sorry for the bad screenshot)
![0F89A600-7B3B-4D32-A205-4172CF664E42](https://user-images.githubusercontent.com/85180696/197349619-8777d321-99b3-4d9c-817c-81f546eff672.jpeg)

ℹ️ Some info 
 - I installed the version 1.0.6 from zero
 - I restarted Obsidian before testing 

I hope you could reproduce this situation on your lend 🙏

Have a great day!

**Comment by ieviev** [comment]
@FelipeRearden ah i think it's something with the yaml tags - i'll see if i can find it

**Comment by FelipeRearden** [comment]
> @FelipeRearden ah i think it's something with the yaml tags - i'll see if i can find it

Ok @aciq ! I hope you find the issue 🙏🙏🙏

**Comment by ieviev** [comment]
@FelipeRearden 

found the issue,
this currently happens when you have a yaml tags list that is null.
like this
![image](https://user-images.githubusercontent.com/36763595/197353060-58c62cb4-603b-4edc-b6cd-fd255be3aca3.png)

i'll fix it soon

**Comment by FelipeRearden** [comment]
> found the issue,
> 
> this currently happens when you have a yaml tags list that is null.


That's great news @aciq !!!!!!!!

> i'll fix it soon

Perfect! I get back to you after the next release :)

**Comment by FelipeRearden** [comment]
Working perfect on version `1.0.7` . Thank you very much for this @aciq !!!!

You have idea how these 3 features are important for my workflow. Thank you very much :)
