### ISSUE TITLE
[Feature Request] Search by Tags → Multiple Inputs

### ISSUE THREAD

**Issue by FelipeRearden** [ieviev/obsidian-keyboard-shortcuts#3]
Hello @aciq !!!

The most important thing about uses tags is the ability to find notes crossing tags. AQS does an amazing job letting us search for notes with moire than one tag as input.

This FR is about supporting multiple tags when selecting a tag from the modal before inserting then in the AQS modal.

## Example  

Lets assume this is my tags:
```
#Source/Books
#Source/Articles
#Source/Podcasts

#Creator/Tim_Ferriss
#Creator/Ryan_Holiday

#Done
```

🔎 And I want to search for notes with the tag `#Source/Books` **AND** `#Creator/Ryan_Holiday` 

## My Idea

1️⃣ If we hit the keyboard <kbd>Mod + ENTER</kbd> when selecting a tag from the Modal it will **insert**  the tag in the text field modal and keep the modal open 
→ This way I could add more tags to text field

2️⃣ When I finish my multiple selection, I hit <kbd>ENTER</kbd> to select the last tag and go to AQS modal with three tags in the search field

📸 Following my example, AQS would get this : 
![97E069F1-D8E2-45C6-B7A7-5C93DEE17E14](https://user-images.githubusercontent.com/85180696/196536475-bf0ec858-0f83-475d-afb6-ad46dc2ead01.jpeg)

---

I hope you like my idea 🙏

Let my know if you need more information !

Thanks for reading this!

**Comment by ieviev** [comment]
Added in #2

**Comment by FelipeRearden** [comment]
Working perfect on version `1.0.7` . Thank you very much for this @aciq !!!!

You have idea how these 3 features are important for my workflow. Thank you very much :)
