### ISSUE TITLE
[Feature Request] New Command → Search By Clipboard

### ISSUE THREAD

**Issue by FelipeRearden** [ieviev/obsidian-keyboard-shortcuts#4]
Hello again @aciq !!!!!

I have another workflow that I wanted to share with you.

The FR is divided by two Features:

### 1️⃣

A new command that is a variation of what **Search by Tag** does by using the `Clipboard` instead of a Modal

### 2️⃣

A NEW Modal Command option in the Settings to let the user define a **different command from Search By Tag**.
⦿ My idea is to use this new Command connected with a different Plugin than AQS.;
⦿ Thats why I am suggesting another.

Let me present below...

## My Workflow

I use the plugin [Omnisearch](https://github.com/scambier/obsidian-omnisearch#omnisearch-for-obsidian) When I want to search for content **inside the note**  

It's a powerful plugin that opens a MODAL to let users search for content **inside the note instead** of only the *filename* in two ways:
→  Search for content inside the Active Note
→  Search for content inside of **ANY** Note in the Vault.

Since I use Obsidian 98% of the time only with the keyboard, search for content using the Search Core Plugin is a nightmare, I use use Omnisearch to keep my hands in the keyboard.

Be able to automatic copy the content of the clipboard while doing a search would be amazing and save a precious time :)

---
Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by ieviev** [comment]
i haven't used omnisearch yet

so far "Another Quick Switcher: Header floating search in file" has been very good for in-file searches for me

i will report back when i have installed and tried omnisearch for a bit

**Comment by FelipeRearden** [comment]
> i haven't used omnisearch yet
> 
> so far "Another Quick Switcher: Header floating search in file" has been very good for in-file searches for me

My perfect combo for search inside Obsidian is AQS for Search Query + in-file Header Search AND Omnisearch for a fast search of content that are in my vault. 
 
Omnisearch is perfect when you are writing/reading something and need to perform a quick search in other notes of a term that you have in the active note. 

> i will report back when i have installed and tried omnisearch for a bit

Thank you very much @aciq !!!

**Comment by ieviev** [comment]
@FelipeRearden 

i used omnisearch for a bit and it really is much better than the default

i think the clipboard shortcut is such a personal thing it should rather be done in AutoHotkey on windows or Autokey on linux.

for example something like this when you highlight text
```
keyboard.send_keys('<ctrl>+c')
keyboard.send_keys('your-omnisearch-shortcut')
keyboard.send_keys('<ctrl>+v')
```

both programs also allow you to set a keyboard shortcut to only obsidian specifically

**Comment by FelipeRearden** [comment]
> i think the clipboard shortcut is such a personal thing it should rather be done in AutoHotkey on windows or Autokey on linux.

100% understood. I appreciate your suggestions about a workaround. My main motivation for this FR is related to my workflow:
- I use Obsidian both on Desktop and Mobile;
- iPadOS with keyboard and mouse.

On Desktop I do exactly what you said using Shell Commands plugin to run a terminal command to put the clipboard inside the Modal. 

My problem is that I **can't** do this on Mobile (iPadOS) because Apple don't expose Terminal.

--- 

Feel absolutely free to close this issue. My intention with this message is too show my entire environment.
- It's been a journey to create a workflow that could be mirrored between these two devices. 

Thanks for this amazing plugin :) I let you know if I have more FR to suggest to you :)
