### ISSUE TITLE
[BUG] Folded Search by Tag: CRTL+ENTER not working on Obsidian Mobile on iOS

### ISSUE THREAD

**Issue by FelipeRearden** [ieviev/obsidian-keyboard-shortcuts#5]
Hello @aciq !!!!!

I use Obsidian on Desktop and on Mobile on iPad with mouse and keyboard.

This way, I identify that <kbd>CRTL+ENTER</kbd> is not working on Obsidian Mobile on iPadOS

I reallly appreciate if you could change the hotkey to <kbd>MOD+ENTER</kbd>  🙏

![2A42B8ED-8F0D-451A-89A5-BD47E0BD19B0](https://user-images.githubusercontent.com/85180696/202864425-0804beb3-7779-4564-8490-3cf60259bba3.jpeg)

ℹ️ **One Important Information**

Just to let you know that <kbd>MOD+</kbd> commands on AQS are working perfect. I tried before writing this post. 

Maybe is something possible to solve 🙏

![141FBDEF-1548-473C-9F56-A1C3D935E743](https://user-images.githubusercontent.com/85180696/202864490-d1c09b51-5971-48b3-8a36-afea4d3b9b99.jpeg)

---

Let me know if you need more information 

Thank you very much !

Have a grea day!

**Comment by ieviev** [comment]
@FelipeRearden 

i added Mod key along with Ctrl in 1.0.8 

see if it works now

**Comment by FelipeRearden** [comment]
> @FelipeRearden
> 
> i added Mod key along with Ctrl in 1.0.8
> 
> see if it works now

Working absolutely **perfect** on version `1.0.8` Obsidian Mobile `1.4.1` . Thank you very much @aciq for the quick reply !!!!!!!!

I tested all hotkeys SHIFT+ENTER and SHIFT+TAB and everything is working.

Thank again @aciq for such an amazing plugin !!!!!!
